v3.0.0

diff --git a/vssh b/vssh
--- a/vssh
+++ b/vssh
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 #
 # Quickly ssh into a vagrant box, or run a command
 # over SSH. CDs into the current directory relative
@@ -6,56 +6,32 @@
 #
 # Caches `vagrant ssh-config` to achieve the speed.
 #
-# Generic commands (accessible anywhere):
-# --version    displays the version of vssh
-# --help       displays help
-#
-# Commands (accessible under a vagrant dir)
-# --config     generate a new vssh config
-# --refresh    refresh ssh config from vagrant
-VERSION="2.1.5"
+
+VERSION="3.0.0"
 DEFAULT_ROOT='/vagrant'
 
 args="${@}"
 exec_dir="${PWD}"
 vagrant_dir="${PWD}"
 
-main()
-{
-  parse_generic_commands
-
-  find_vagrant_dir
-  parse_commands
-
-  find_vssh_config
-  find_ssh_config
-
-  ssh_connect
-}
-
-parse_generic_commands()
-{
-  if [ "${args[0]}" = "--version" ]; then
-    echo ${VERSION}
-
-    exit 0
-  fi
-
-  if [ "${args[0]}" = "--help" ]; then
-    echo "$(help)"
-
-    exit 0
-  fi
-}
+SSH_CONFIG=".vagrant/ssh_config"
 
 help()
 {
-  echo "${VERSION}\n\
-        \nUsage: vssh [options] [command]\
-        \n  --version\tPrint the vssh version\
-        \n  --help\tDisplay this message\
-        \n  --config\tInteractively generate a new vssh config\
-        \n  --refresh\tRefresh ssh config cache from Vagrant"
+  cat<<EOF
+  ${VERSION}
+  Usage: 
+    vssh [options] 
+
+  -v    Print the vssh version
+  -h    Display this message
+  -r    Interactively generate a new vssh config (do this first!)
+
+  or
+    vssh remote_host [-c "command(s)"]
+
+  -c  Execute this command on the remote host
+EOF
 }
 
 
@@ -102,51 +78,19 @@ vssh_config_path()
     echo "${PWD}/.vagrant/vssh.cfg"
 }
 
-generate_vssh_config()
-{
-  read -p "root [${DEFAULT_ROOT}]: " root
-
-  if [ "${root}" == "" ]; then root="${DEFAULT_ROOT}"; fi
-
-  echo "root=\"${root}\"" > "$(vssh_config_path)"
-
-  echo ""
-}
-
 parse_vssh_config()
 {
   source "$(vssh_config_path)"
 }
 
-parse_commands()
-{
-  if [ "${args[0]}" = "--config" ]; then
-    # remove --config from args
-    args=("${args[@]:1}")
-
-    echo "Generating new vssh config."
-
-    generate_vssh_config
-  fi
-
-  if [ "${args[0]}" = "--refresh" ]; then
-    # remove --refresh from args
-    args=("${args[@]:1}")
-
-    echo "Refreshing vagrant ssh config."
-
-    generate_ssh_config
-  fi
-}
-
 generate_ssh_config()
 {
-  vagrant ssh-config > .vagrant/ssh_config
+  vagrant ssh-config > $SSH_CONFIG
 }
 
 find_ssh_config()
 {
-  if ! [ -a .vagrant/ssh_config ]; then
+  if ! [ -a $SSH_CONFIG ]; then
     echo "Vagrant ssh config not found; generating."
 
     generate_ssh_config
@@ -155,7 +99,11 @@ find_ssh_config()
 
 ssh_connect()
 {
-    ssh -F .vagrant/ssh_config -t default "cd $(box_dir); $(ssh_command)"\
+    remote_host=$1
+    shift
+    command=$1
+    shift
+    ssh -F $SSH_CONFIG -t $remote_host "$command"\
         3>&1 1>&2 2>&3 3>&-
 }
 
@@ -175,4 +123,51 @@ ssh_command()
   fi
 }
 
-main
+###############################################################################################
+#
+# main
+#
+
+ARGS=() ### this array holds any positional arguments, i.e., arguments not started with dash
+
+while [ $# -gt 0 ]; do
+    while getopts :hvrc: name; do
+        case $name in
+          h) # display Help
+            help
+            exit;;
+          v) # display version
+            echo "Version: $VERSION"
+            exit;;
+          r) # create config
+            echo "Generating a new "
+            generate_ssh_config
+            exit;;
+          c) # Enter a name
+            command=$OPTARG;;
+          \?) # Invalid option
+            echo "Error: Invalid option"
+            exit;;
+        esac
+    done
+    [ $? -eq 0 ] || exit 1
+    [ $OPTIND -gt $# ] && break   # we reach end of parameters
+
+    shift $[$OPTIND - 1] # free processed options so far
+    OPTIND=1             # we must reset OPTIND
+    ARGS[${#ARGS[*]}]=$1 # save first non-option argument (a.k.a. positional argument)
+    shift                # remove saved arg
+done
+
+if [[ ${#ARGS[*]} -ne 1 ]]; then
+  echo "ERROR:only one postitional parameter expected ie. a remote_hostname"
+  help
+  exit 1
+fi
+
+find_vagrant_dir
+
+find_ssh_config
+
+remote_host=${ARGS[0]}
+ssh_connect "$remote_host" "$command"
